apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pull-test
  name: pull-test
  namespace: pull-issue
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: pull-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pull-test
    spec:
      nodeName: $NODE
      containers:
      - image: quay.io/pbertera/pull-test:latest
        imagePullPolicy: Always
        name: main
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
